<?php

$labels = array();
$labels['autoresponder'] = 'Automatische Antworten Einrichten';
$labels['autorespondersubject'] = 'Betreff:';
$labels['autorespondermessage'] = 'Nachricht:';
$labels['autoresponderexpires'] = 'Automatische Antworten abschalten am:';
$labels['autoresponderdatefrom'] = 'Erster Tag:';
$labels['autoresponderdate'] = 'Letzter Tag:';
$labels['autoresponderenabled'] = 'Automatische Antworten aktiv:';
$labels['dateformat'] = 'TT.MM.JJJJ';
$labels['and'] = 'und';

$labels['pfamin_autoresponder'] = 'Automatische Antworten';

$messages = array();
$messages['dateformatinconsistency'] = 'Die Eingabe passt nicht zu einem Datum';
$messages['entervalidmonth'] = 'Bitte einen korrekten Monat angeben.';
$messages['entervalidday'] = 'Bitte einen korrekten Tag angeben.';
$messages['enterfordigityear'] = 'Ein Jahr (vier Stellen) angeben, zwischen';
$messages['entervaliddate'] = 'Bitte ein gültiges Datum angeben.';
$messages['dateinpast'] = 'Das Datum liegt in der Vergangenheit. Damit bleibt die automatische Antwort aktiv, bis sie manuell abgeschaltet wird!';
$messages['subjectempty'] = 'Bitte einen Betreff angeben';
$messages['demoaccount'] = 'Das ist ein Demokonto. Automatische Antworten können nicht verwendet werden.';

?>
